- include_vars: images-vars.yml

# - name: tuleap-aio-dev image
#   openshift_imagestream:
#     metadata:
#       name: tuleap-aio-dev
#       namespace: "{{ k8s_namespace }}"
#     from: "{{ tuleap_aio_dev_image_name_and_tag }}"
#     tag: latest

- name: tuleap built image
  openshift:
    state: latest
    content: |
      apiVersion: image.openshift.io/v1
      kind: ImageStream
      metadata:
        name: tuleap
        namespace: "{{ k8s_namespace }}"
      spec: {}

- name: build tuleap image with latest release version
  openshift:
    state: latest
    content: |
      apiVersion: build.openshift.io/v1
      kind: BuildConfig
      metadata:
        name: tuleap
        namespace: "{{ k8s_namespace }}"
        labels:
          build:   tuleap
          team:    idev-fsd
          app:     tuleap
      spec:
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        output:
          to:
            kind: ImageStreamTag
            name: 'tuleap:latest'
        source:
          type: Git
          contextDir: "{{ tuleap_build_repo_context }}"
          git:
            uri: "{{ tuleap_build_repo_url }}"
            ref: "master"
        strategy:
          dockerStrategy:
            noCache: true
          type: Docker
        triggers: []
