# To edit the encrypted secrets below, you need eyaml installed.
# Familiarize yourself with
# https://puppet.com/blog/encrypt-your-data-using-hiera-eyaml first.
# The edit command goes like this,
#
#   eyaml edit -d \
#     --pkcs7-public-key eyaml/epfl_tuleap_prod.pem \
#     roles/tuleap-namespace/vars/mysql-vars.yml
#
# 💡 This *will not* decrypt anything for you because chances are, you
# don't need to decrypt secrets (YA RLY). For those cases where you
# do, wielding the private key from Keybase is left as an exercise to
# the reader.
mysql_credentials:
  super:
    database: tuleap_prod
    host: mysql-scx
    port: 33001
    user: tuleap_super
    password: ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAH8uijjJbZPTNuWIlwOTA9aA1U1S1bEvYa7E7Jy9lE9mRBl8W22Q8LWJ2V2fGwezK+Y4yAEwLQQW4cprc6Ow1ftBle34kJeFngKp0pnKCrFYhUml+x4mDlRcgWsJ+IeceNNv9mkhh9OK+/zomW4aCdqK10190zun6giRiGFvXAfTY3ZIAK6N/TwDCd6JGTtLWRhHOhsF/fedec9h84hUvVUhjg7GVheKcHLw4r3mDYNo9JaEOixz3vAmkWE+WMdH2I0fi3Ivx0RVUEOXKZh+JwCkb11K66ZPNHjy7pJHAKGie+RwXP7+K6OQ/gWv5cRR8dLUaZCQr+2uJP/NXIGEGjDA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBDbdJl1Pmho7ucCQoAkNVx6gBDNbX/lcpg7OxA9gWIphOXM]
  web:
    database: tuleap_prod
    host: mysql-scx
    port: 33001
    user: tuleap_web
    password: ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEASZj1yZDCx/27Lwbnv56BIYvZnsZ8hyjltMf/63rCT/CrTGOfhr3IBdblbn5vGYNULw8XhCkfYC6wtQIX+VeGotjUvNZAQEy3RLYdbSP0Or42St7BS8OZjUjkt6dXT2m4BehaX3xEM0YFn7S9s8S8+GxviOJsuBNc3QxMS+ZrdzKoRgG50GQMyOs+X7J0VqxZs+jo0FhGCHGqUarWMJpoRI+ERASEJ9WwXWBeozGWav0jlnKn28JY33r4xqfq2ejhv9WEnl9dcVVKQRQCnaMyx05+D0PNmS7GMwIFHkUkAfL7sWjgE7FKfvmqFUgsD6/wN7vgBe7dPsnhj8sgGdGqwTA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBCgKwiJK6uHzKME1dJJrICqgBCV0yX1B5Gw/EfEoLdA9rG0]
  local:
    host: localhost
    root_password: ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEACFCnRLjYcJk9GPZ/mnj2qrN5Ktb2m2Fc9l27eJ4A9YTR7f+MMS9m+AZrD9kNUukG1xCbo2+pXcz+xms2x6cor9hM89r4evqo+TlpweR9yUPlnwR18NaNvdvlHSO3tN1gPQbUmCYsRXiKd+ctt96luK9jkXE0+SdUaN7g49xyQDNfZQUUJzA34Ie6MF3uFZoXSLtC6DCWuBhKrfYxmw2pEloVmDt/8oYSK5x6xwj7kZWmEI2XOT5531vNMT97kHerqwiuV54k3HzOxwYSh/nmEtq+68jerzFA4bjQLx5HReNs1gQOTG5BKhp6od/Qi4fyBoMc/l9WSPhOvd+aIllxtzA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBDfBYcfqknGdvVK58SYtorIgBA5cBhvxvQurRJ/Qe/stB9d]
    default_root_password: ""
