- name: Ensure mysql installed
  package:
    name: "{{ item }}"
    state: present
  loop:
    - rh-mysql57-mysql
    - rh-mysql57-mysql-server
    - MySQL-python

- name: enable mysql service
  service:
    name: rh-mysql57-mysqld
    enabled: yes
    state: started

# - name: Ensure tuleap packages
#   package:
#     name: "{{ item }}"
#     state: present
#   loop:
#     - tuleap 
#     - tuleap-plugin-agiledashboard 
#     - tuleap-plugin-graphontrackers 
#     - tuleap-theme-burningparrot 
#     - tuleap-theme-flamingparrot 
#     - tuleap-plugin-ldap
#     - tuleap-plugin-git 
#     - tuleap-plugin-pullrequest

# Installing with yum with the hope that the issue with git repos was due to 
# the fact that packages were not installed at the same time / correct order
- name: Ensure tuleap packages
  yum:
    name:
      - tuleap 
      - tuleap-plugin-agiledashboard 
      - tuleap-plugin-graphontrackers 
      - tuleap-theme-burningparrot 
      - tuleap-theme-flamingparrot 
      - tuleap-plugin-ldap
      - tuleap-plugin-git 
      - tuleap-plugin-pullrequest
    state: present


# # The following plugins have missing dependencies on RHEL (sclo-git212-git)
# - name: Ensure (CentOS only) tuleap plugins
#   package:
#     name: "{{ item }}"
#     state: present
#   loop:
#     - tuleap-plugin-git 
#     - tuleap-plugin-pullrequest
#   when: ansible_distribution == 'CentOS' 

- name: patch LDAP plugin to accept multiple entry patch for ldap search
  lineinfile: 
    path: /usr/share/tuleap/plugins/ldap/include/LDAP.class.php
    regexp: 'if \(\$lri && count\(\$lri\) === 1\)'
    line: '        if ($lri && count($lri) > 0) {'
    create: no


