- name: Disable SELinux
  selinux:
    state: disabled

- name: Ensure EPEL repo
  package:
    name: epel-release
    state: present

- name: Ensure release-scl repo
  package:
    name: centos-release-scl
    state: present

- name: Ensure Remi repo
  package:
    name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: Ensure Tuleap repo
  yum_repository:
    name: tuleap
    description: Tuleap
    state: present
    repo_gpgcheck: no
    enabled: yes
    baseurl: https://ci.tuleap.net/yum/tuleap/rhel/7/dev/x86_64/
    gpgkey: https://ci.tuleap.net/yum/tuleap/gpg.key

- name: Ensure mysql installed
  package:
    name: "{{ item }}"
    state: present
  loop:
    - rh-mysql57-mysql
    - rh-mysql57-mysql-server
    - MySQL-python

- name: enable mysql service
  service:
    name: rh-mysql57-mysqld
    enabled: yes
    state: started

- name: Ensure tuleap packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - tuleap 
    - tuleap-plugin-agiledashboard 
    - tuleap-plugin-graphontrackers 
    - tuleap-theme-burningparrot 
    - tuleap-theme-flamingparrot 
    - tuleap-plugin-git 
    - tuleap-plugin-pullrequest
    - tuleap-plugin-ldap

- name: patch LDAP plugin to accept multiple entry patch for ldap search
  lineinfile: 
    path: /usr/share/tuleap/plugins/ldap/include/LDAP.class.php
    regexp: 'if \(\$lri && count\(\$lri\) === 1\)'
    line: '        if ($lri && count($lri) > 0) {'
    create: no