
# To just debug: ./tulsible -l vagrant -t tmp
- name: Debug
  import_tasks: tmp.yml
  tags: tmp

- name: Install Tuleap
  import_tasks: install.yml
  tags: install

- name: Configure Tuleap
  import_tasks: configure.yml
  tags: config


